### DISCUSSION TITLE
Solarman configuration for Solis Single Phase Inverter (S5-GR1P(3-6)K)

### DISCUSSION THREAD

**Discussion by ChirpyTurnip** [StephanJoubert/home_assistant_solarman#185] [Show and tell]
Hi,

Here is my working config for a Solis S5-GR1P(3-6)K single phase inverter. I use Node Red to break the bit-based errors down into actual useful messages. 

```
# Solis Single Phase
# S5-GR1P(3-6)K
# Modbus information retrieved from:
# https://www.scss.tcd.ie/coghlan/Elios4you/RS485_MODBUS-Hybrid-BACoghlan-201811228-1854.pdf
# Entries marked #OK seem to work correctly, those marked #BORKED are not yet working. 

requests:
  - start: 3000
    end:  3075
    mb_functioncode: 0x04

parameters:
 - group: Generation_Summary
   items: 
    - name: "Inverter Active Power" #OK
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 4
      registers: [3005,3006]
      icon: 'mdi:transmission-tower'

    - name: "Inverter DC Power" #OK
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 1
      rule: 3
      registers: [3007,3008]
      icon: 'mdi:solar-power'

    - name: "Total Generation" #OK
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 1
      rule: 3
      registers: [3009,3010]
      icon: 'mdi:solar-power'

    - name: "Monthly Generation" #OK
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 1
      rule: 3
      registers: [3011,3012]
      icon: 'mdi:solar-power'

    - name: "Daily Generation" #OK
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [3014]
      icon: 'mdi:solar-power'

    - name: "Yearly Generation" #OK
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 1
      rule: 3
      registers: [3017,3018]
      icon: 'mdi:solar-power'


 - group: Inverter_DC
   items: 
    - name: "PV1 Voltage" #OK
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [3021]
      icon: 'mdi:solar-power'

    - name: "PV1 Current" #OK
      class: "current"
      uom: "A"
      scale: 0.1
      rule: 1
      registers: [3022]
      icon: 'mdi:current-dc'

    - name: "PV2 Voltage" #OK
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [3023]
      icon: 'mdi:solar-power'

    - name: "PV2 Current" #OK
      class: "current"
      state_class: "measurement"
      uom: "A"
      scale: 0.1
      rule: 1
      registers: [3024]
      icon: 'mdi:current-dc'


 - group: Inverter_Status
   items: 
    - name: "Inverter Voltage" #OK
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [3035]
      icon: 'mdi:transmission-tower'

    - name: "Inverter Current" #OK, relative to apparent power
      class: "current"
      state_class: "measurement"
      uom: "A"
      scale: 0.1
      rule: 1
      registers: [3038]
      icon: 'mdi:current-ac'

# Full definition if you want in-place lookup/conversion
#    - name: "Working Mode" #OK
#      class: ""
#      state_class: ""
#      uom: ""
#      scale: 1
#      rule: 1
#      registers: [3040]
#      isstr: true
#      lookup: 
#      - key: 0
#        value: "No Response"
#      - key: 1
#        value: "Volt-Watt"
#      - key: 2
#        value: "Volt-VAr"
#      - key: 3
#        value: "Fixed PF"
#      - key: 4
#        value: "Fixed VAr"
#      - key: 5
#        value: "Power-PF"
#      - key: 6
#        value: "Rule21"
#      icon: 'mdi:home-lightning-bolt'

# Output only version if you do conversion in Node Red
    - name: "Working Mode" #OK
      class: ""
      state_class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [3040]
      isstr: true
      icon: 'mdi:home-lightning-bolt'

    - name: "Inverter Temperature" #OK
      class: "temperature"
      state_class: "measurement"      
      uom: "°C"
      scale: 0.1
      rule: 2
      registers: [3041]
      icon: 'mdi:thermometer'

# Full definition if you want in-place lookup/conversion
#    - name: "Inverter Status" #OK
#      class: ""
#      state_class: ""      
#      uom: ""
#      scale: 1
#      rule: 1
#      registers: [3043]
#      isstr: true
#      lookup: 
#      - key: 0
#        value: "Stand-by"
#      - key: 1
#        value: "Open Run"
#      - key: 2
#        value: "Soft Run"
#      - key: 3
#        value: "Generating"
#      icon: 'mdi:home-lightning-bolt'

# Output only version if you do conversion in Node Red
    - name: "Inverter Frequency" #OK
      class: "frequency"
      state_class: "measurement"
      uom: "Hz"
      scale: 0.01
      rule: 1
      registers: [3042]
      icon: 'mdi:sine-wave'

    - name: "Inverter Status" #OK
      class: ""
      state_class: ""
      uom: ""
      scale: 1
      rule: 1
      registers: [3043]
      isstr: true
      icon: 'mdi:home-lightning-bolt'

    - name: "Inverter Reactive Power" #OK
      class: "reactive_power"
      state_class: "measurement"
      uom: "VAr"
      scale: 1
      rule: 4
      registers: [3056]
      icon: 'mdi:transmission-tower'
    
    - name: "Inverter Apparent Power" #OK
      class: "apparent_power"
      state_class: "measurement"
      uom: "VA"
      scale: 1
      rule: 4
      registers: [3058]
      icon: 'mdi:transmission-tower'


 - group: Alarms
   items:
    - name: "Fault Status 01 (Grid)" #OK, Convert in Node Red
      class: ""
      state_class: ""
      uom: ""
      scale: 1
      rule: 2
      registers: [3066]
      icon: 'mdi:alert'

    - name: "Fault Status 02 (DC)" #OK, Convert in Node Red
      class: ""
      state_class: ""
      uom: ""
      scale: 1
      rule: 2
      registers: [3067]
      icon: 'mdi:alert'

    - name: "Fault Status 03 (Protection)" #OK, Convert in Node RedED
      class: ""
      state_class: ""
      uom: ""
      scale: 1
      rule: 2
      registers: [3068]
      icon: 'mdi:alert'

    - name: "Fault Status 04 (Device)" #OK, Convert in Node Red
      class: ""
      state_class: ""
      uom: ""
      scale: 1
      rule: 2
      registers: [3069]
      icon: 'mdi:alert'

    - name: "Working Status" #OK, Convert in Node Red
      class: ""
      state_class: ""
      uom: ""
      scale: 1
      rule: 2
      registers: [3071]
      icon: 'mdi:home-lightning-bolt'
```
