### DISCUSSION TITLE
Bluesun Inverter status say disconnected

### DISCUSSION THREAD

**Discussion by sven0833** [StephanJoubert/home_assistant_solarman#284] [Q&A]
im trying to integrate my bluesun inverter 6kw 

but home assistant just saw the coonection status disconnected. i tried to load all the .yaml file
some say unknown and other say unavailable... i dont know how to fix it can some one help me

**Comment by demand187** [comment]
Hi Sven, I've got the same issue. Have you found a solution yet?

**Comment by sven0833** [comment]
No solution yer

**Reply by demand187** [reply]
Have you tried other ways to connect the inverter besides this integration? There seem to be other solutions to connect inverters connected with Solarman, but I haven't tried them out yet.

**Comment by Funky-0815** [comment]
The following settings worked for me:

Inverter_host: 0.0.0.0 (Auto-discovery)
Inverter_serial: 0 (Auto-discovery)
lookup file: custom_parameters.yaml

I don't know why but I only have a connection with automatic-discovery funktion.

Here the custom_parameters.yaml looks  like that:
(Until now i don't have time to implement more Parameters, but you can find the modbus addresses in the description of [this Video](https://youtu.be/TQTu_iBdNZY?si=ok6VNwKOoSf6KJ5s))


```
# BlueSun BSE8KH3
#
requests:
  - start: 0x3110
    end: 0x311F
    mb_functioncode: 0x03
  - start: 0x3130
    end: 0x313C
    mb_functioncode: 0x03
  - start: 0x313E
    end: 0x314E
    mb_functioncode: 0x03



parameters:

  - group: GRID
    items:
      - name: "Volt_Grid_A"
        class: "energy"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [0x3110]
        icon: "mdi:solar-power"

      - name: "Volt_Grid_B"
        class: "energy"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [0x3113]
        icon: "mdi:solar-power"

      - name: "Volt_Grid_C"
        class: "energy"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [0x3116]
        icon: "mdi:solar-power"

      - name: "Current_Grid_A"
        class: "energy"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 2
        registers: [0x3111]
        icon: "mdi:solar-power"

      - name: "Current_Grid_B"
        class: "energy"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 2
        registers: [0x3114]
        icon: "mdi:solar-power"

      - name: "Current_Grid_C"
        class: "energy"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 2
        registers: [0x3117]
        icon: "mdi:solar-power"

      - name: "Power_Grid_A"
        class: "energy"
        state_class: "measurement"
        uom: "W"
        scale: 1
        rule: 2
        registers: [0x3112]
        icon: "mdi:solar-power"

      - name: "Power_Grid_B"
        class: "energy"
        state_class: "measurement"
        uom: "W"
        scale: 1
        rule: 2
        registers: [0x3115]
        icon: "mdi:solar-power"

      - name: "Power_Grid_C"
        class: "energy"
        state_class: "measurement"
        uom: "W"
        scale: 1
        rule: 2
        registers: [0x3118]
        icon: "mdi:solar-power"

  - group: PV
    items:
      - name: "Power_PV1"
        class: "energy"
        state_class: "measurement"
        uom: "W"
        scale: 1
        rule: 1
        registers: [0x3132]
        icon: "mdi:solar-power"

      - name: "Power_PV2"
        class: "energy"
        state_class: "measurement"
        uom: "W"
        scale: 1
        rule: 1
        registers: [0x3135]
        icon: "mdi:solar-power"

  - group: Bat
    items:
      - name: "Bat_Temp"
        class: "energy"
        state_class: "measurement"
        uom: "°C"
        scale: 0.1
        scale_division: 10
        rule: 1
        registers: [0x3146]
        icon: "mdi:solar-power"

      - name: "Bat_SOC"
        class: "energy"
        state_class: "measurement"
        uom: "%"
        scale: 0.1
        scale_division: 10
        rule: 1
        registers: [0x3145]
        icon: "mdi:solar-power"
```
