### DISCUSSION TITLE
Autoselecting the appropriate inverter definition.

### DISCUSSION THREAD

**Discussion by frsantos** [StephanJoubert/home_assistant_solarman#312] [Ideas]
Hi all,

I've thinking if it would be possible to automatically select one of the inverter definitions based on the serial number. From what I've read on many discussions, each serial inverter definition works only for a subset of serial numbers, so auto selecting an adequate definition would be just a matter of adding a list of supported serial number ranges to each definition file, and some code to match them against the configured one.

If we add some info to the definition about which request we need to perform to get the SN, we can even make it completely automatic (maybe even the IP/port can be auto-discovered too?). Of course, that is just a "wizardry" thing for initial configuration after installation, but it can be manually selected as now.

So, the inverter file would have something like the following:

```yaml
info:
  name: 'Inverter name'
  accepted_sns:
    - start: 127000000
      end:   127999999
    - start: 130000000
      end:   130999999 
  sn_request:
    mb_functioncode: 0x04
    registers: [3228, 3229, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238]
    rule: 5

requests:
  ....
parameters:
  ....
```
What do you think, is it doable?

**Comment by frsantos** [comment]
Inverters are usually rebranded with different names, but under the hood they are the same. So, another improvement could be to add the different inverter names that are known to work with a definition file, and show them to the user when selecting a definition file. Something like "This definition file is known to work with the following inverters: ..."

And again, sometimes the actual inverter name can be even be retrieved with another request: "This inverter references itself as ..."

So, now we may have something like:

```yaml
info:
  accepted_sns:
    - start: 127000000
      end:   127999999
    - start: 130000000
      end:   130999999 
  sn_request:
    mb_functioncode: 0x04
    registers: [3228, 3229, 3230, 3231, 3232, 3233, 3234, 3235, 3236, 3237, 3238]
    rule: 5

  inverter_names:
    - Some Inverter
    - A different brand inverter
    - ...
  inverter_names_request:
    mb_functioncode: 0x03
    registers: [3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207]
    rule: 5

requests:
  ....
parameters:
  ....
```
