### DISCUSSION TITLE
Solarman integration with Zucchetti ZCS 3000 Hybrid (ita and eng)

### DISCUSSION THREAD

**Discussion by Bilo2110** [StephanJoubert/home_assistant_solarman#346] [Q&A]
Ciao a tutti, anche io non riesco a far funzionare l'integrazione solarman con il mio inveter azzurro hybrid 3000.
Alcune configurazioni yaml mi danno delle informazioni, altre no... Quella 'più completa" mi sembra la zcs_azzurro_ktl-v3...
Quella che dovrebbe essere la sua (la sofar_hyd3k-6k-es.yaml) non mi da nessun dato... Qualcuno che aiuti anche me?

Hi everyone, I also can't get the solarman integration to work with my azzurro  hybrid 3000 inverter.
 Some yaml configurations give me information, others don't... The 'most complete' one seems to me the zcs_azzurro_ktl-v3...
 The one that should be yours (the sofar_hyd3k-6k-es.yaml) doesn't give me any data... Can someone help me too?

**Comment by double1968** [comment]
Try my setup I use on HYD4000 ZSS

Prova la mia configurazione che uso su HYD4000 ZSS

```
requests:
  - start: 0x0200
    end:  0x021F
    mb_functioncode: 0x03
  - start: 0x0220
    end: 0x0255
    mb_functioncode: 0x03


parameters:
 - group: Generation
   items:
    - name: "Generation Power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 10
      rule: 1
      registers: [0x0215]
      icon: 'mdi:solar-power'

    - name: "Daily Production"
      class: "energy"
      state_class: "measurement"      
      uom: "KWh"
      scale: 0.01
      rule: 1
      registers: [0x0218]
      icon: 'mdi:solar-power'

    - name: "Total Production"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 1
      rule: 1
      registers: [0x021D,0x021C]
      icon: 'mdi:solar-power'

    - name: "Generation Today Time"
      class: "time"
      state_class: "measurement"      
      uom: "min"
      scale: 1
      rule: 1
      registers: [0x0243]
      icon: 'mdi:sun-clock-outline'

    - name: "Generation Total Time"
      class: "duration"
      state_class: "total_increasing"
      uom: "h"
      scale: 1
      rule: 1
      registers: [0x0245,0x244]
      icon: 'mdi:sun-clock-outline'

    - name: "Generation Solar PV1"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 10
      rule: 1
      registers: [0x0252]
      icon: 'mdi:solar-power'

    - name: "Generation Solar PV2"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 10
      rule: 1
      registers: [0x0255]
      icon: 'mdi:solar-power'

 - group: Load
   items:
    - name: "Load Consumption Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 10
      rule: 1
      registers: [0x0213]
      icon: 'mdi:home-lightning-bolt'

    - name: "Load Daily Consumption"
      class: "energy"
      state_class: "measurement"      
      uom: "KWh"
      scale: 0.01
      rule: 1
      registers: [0x021B]
      icon: 'mdi:home-lightning-bolt'

    - name: "Load Total Consumption"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 1
      rule: 1
      registers: [0x0223,0x0222]
      icon: 'mdi:home-lightning-bolt-outline'

 - group: Grid
   items:
    - name: "Grid Voltage"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0206]
      icon: 'mdi:transmission-tower'

    - name: "Grid Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x0207]
      icon: 'mdi:current-ac'

    - name: "Grid freq"
      class: "frequency"
      state_class: "measurement"      
      uom: "Hz"
      scale: 0.01
      rule: 1
      registers: [0x020C]
      icon: 'mdi:sine-wave'

    - name: "Energy Exported Today"
      class: "energy"
      state_class: "measurement"      
      uom: "KWh"
      scale: 0.01
      rule: 1
      registers: [0x0219]
      icon: 'mdi:transmission-tower-export'

    - name: "Energy Imported Today"
      class: "energy"
      state_class: "measurement"      
      uom: "KWh"
      scale: 0.01
      rule: 1
      registers: [0x021A]
      icon: 'mdi:transmission-tower-import'

    - name: "Grid Total Energy exported"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 1
      rule: 1
      registers: [0x021F,0x021E]
      icon: 'mdi:transmission-tower-export'

    - name: "Grid Total Energy purchase"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 1
      rule: 1
      registers: [0x0221,0x0220]
      icon: 'mdi:transmission-tower-import'

    - name: "Grid R Voltage"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0230]
      icon: ''

    - name: "Grid R Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 1
      registers: [0x0231]
      icon: ''

 - group: Battery
   items:
    - name: "Battery Power Cha/Dis"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 10
      rule: 2
      registers: [0x020D]
      icon: 'mdi:home-battery'

    - name: "Batt Charge Today"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.01
      rule: 1
      registers: [0x0224]
      icon: 'mdi:battery-arrow-up'

    - name: "Batt Discharge Today"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.01
      rule: 1
      registers: [0x0225]
      icon: 'mdi:battery-arrow-down'

    - name: "Battery Total Charging Energy"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.01
      rule: 1
      registers: [0x0227,0x0226]
      icon: 'mdi:battery-arrow-up'

    - name: "Battery Total Discharging Energy"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.01
      rule: 1
      registers: [0x0229,0x0228]
      icon: 'mdi:battery-arrow-down'

    - name: "Battery Total Charge/Discharge Cycles"
      class: ""
      state_class: "total_increasing"
      uom: ""
      scale: 1
      rule: 1
      registers: [0x022C]
      icon: 'mdi:home-battery'

    - name: "Battery SOH"
      class: ""
      state_class: "measurement"
      uom: "%"
      scale: 1
      rule: 1
      registers: [0x0237]
      icon: 'mdi:home-battery'

    - name: "Battery SOC"
      class: "battery"
      state_class: "measurement"
      uom: "%"
      scale: 1
      rule: 1
      registers: [0x210]
      icon: 'mdi:battery'

    - name: "Battery Temperature"
      class: "temperature"
      state_class: "measurement"      
      uom: "°C"
      scale: 1
      rule: 1
      registers: [0x0211]
      icon: 'mdi:thermometer'  

    - name: "Battery voltage"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x020E]
      icon: 'mdi:home-lightning-bolt'

    - name: "Battery Cha/Dis current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 2
      registers: [0x020F]
      icon: 'mdi:home-lightning-bolt'

 - group: Output
   items:
    - name: "Out Grid power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 10
      rule: 2
      registers: [0x0212]
      icon: 'mdi:transmission-tower'

    - name: "Output/Input power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 10
      rule: 2
      registers: [0x0214]
      icon: 'mdi:transmission-tower'

 - group: Inverter
   items: 
    - name: "Inverter Running state"
      class: ""
      state_class: "measurement"      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0200]
      lookup: 
      -  key: 0
         value: "Wait State"
      -  key: 1
         value: "Check State"
      -  key: 2
         value: "Normal State"
      -  key: 3
         value: "Discharging Check State"
      -  key: 4
         value: "Discharging State"
      -  key: 5
         value: "EPS State"
      -  key: 6
         value: "Fault State"
      -  key: 7
         value: "Permanent State"
      icon: 'mdi:wrench'         

    - name: "Inverter HStemp"
      class: "temperature"
      uom: "°C"
      scale: 1
      rule: 2
      registers: [0x0239]
      icon: 'mdi:thermometer'

    - name: "Inverter temperature"
      class: "temperature"
      state_class: "measurement"      
      uom: "°C"
      scale: 1
      rule: 2
      registers: [0x0238]
      icon: 'mdi:thermometer'      

    - name: "Inverter Voltage dc component"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 2
      registers: [0x023C]
      icon: 'mdi:home-lightning-bolt'

    - name: "Inverter Current dc component"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.1
      rule: 2
      registers: [0x023B]
      icon: 'mdi:home-lightning-bolt'

    - name: "Inverter bus voltage"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 2
      registers: [0x022D]
      icon: 'mdi:home-lightning-bolt'

    - name: "Inverter LLC bus voltage"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x022E]
      icon: 'mdi:home-lightning-bolt'

    - name: "Inverter Buck current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.1
      rule: 1
      registers: [0x022F]
      icon: 'mdi:home-lightning-bolt'

    - name: "Inverter Countdown time"
      class: ""
      state_class: "measurement"      
      uom: "s"
      scale: 1
      rule: 1
      registers: [0x022A]
      icon: ''

    - name: "Inverter alert message"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x022B]
      icon: ''

    - name: "Inverter Communication Board inner message"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0242]
      icon: ''
      
    - name: "Inverter solarPV1Volt"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 2
      registers: [0x0250]

    - name: "Inverter solarPV1Amps"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 1
      registers: [0x0251]
      icon: ''

    - name: "Inverter solarPV2Volt"
      class: "voltage"
      state_class: "measurement"      
      uom: "V"
      scale: 0.1
      rule: 2
      registers: [0x0253]


    - name: "Inverter solarPV2Amps"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.01
      rule: 1
      registers: [0x0254]
      icon: ''

    - name: "Inverter Country"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x023A]
      lookup: 
      -  key: 0
         value: "Germany"
      -  key: 1
         value: "CEI0-21 Internal"
      -  key: 2
         value: "Australia"
      -  key: 3
         value: "Spain RD1699"
      -  key: 4
         value: "Turkey"
      -  key: 5
         value: "Denmark"
      -  key: 6
         value: "Greece"
      -  key: 7
         value: "Netherland"
      -  key: 8
         value: "Belgium"
      -  key: 9
         value: "UK-G59"
      -  key: 10
         value: "China"
      -  key: 11
         value: "France"
      -  key: 12
         value: "Poland"
      -  key: 13
         value: "Germany BDEW"
      -  key: 14
         value: "Germany VDE0126"
      -  key: 15
         value: "Italy CEI0-16"
      -  key: 16
         value: "UK-G83"
      -  key: 17
         value: "Greece Islands"
      -  key: 18
         value: "EU EN50438"
      -  key: 19
         value: "EU EN61727"
      -  key: 20
         value: "Korea"
      -  key: 21
         value: "Sweden"
      -  key: 22
         value: "Europe General"
      -  key: 23
         value: "CEI0-21 External"
      -  key: 24
         value: "Cyprus"
      -  key: 25
         value: "India"
      -  key: 26
         value: "Philippines"
      -  key: 27
         value: "New Zeland"
      -  key: 28
         value: "Reserve"
      -  key: 29
         value: "Reserve"
      icon: ''

 - group: Alert
   items: 
    - name: "Alert Fault 1"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0201]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "ID01 Grid Over Voltage Protection"
      -  key: 2
         value: "ID02 Grid Under Voltage Protection"
      -  key: 4
         value: "ID03 Grid Over Frequency Protection"
      -  key: 8
         value: "ID04 Grid Under Frequency Protection"
      -  key: 16
         value: "ID05 Battery Over Voltage"
      -  key: 32
         value: "ID06"
      -  key: 64
         value: "ID07"
      -  key: 128
         value: "ID08"
      -  key: 256
         value: "ID09 LLCBus Over Voltage Hardware"
      -  key: 512
         value: "ID10 Bus Over Voltage Hardware"
      -  key: 1024
         value: "ID11 BuckBoost over Current Hardware"
      -  key: 2048
         value: "ID12 Battery over Current Hardware"
      -  key: 4096
         value: "ID13"
      -  key: 8192
         value: "ID14"
      -  key: 16384
         value: "ID15 Output Current Hardware"
      -  key: 32768
         value: "ID16"
      icon: 'mdi:wrench'  

    - name: "Alert Fault 2"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0202]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "ID17 Grid current sampling error"
      -  key: 2
         value: "ID18 DCI sampling error"
      -  key: 4
         value: "ID19 Grid voltage sampling error"
      -  key: 8
         value: "ID20"
      -  key: 16
         value: "ID21 Main chip fault"
      -  key: 32
         value: "ID22 Hardware auxiliary power fault"
      -  key: 64
         value: "ID23"
      -  key: 128
         value: "ID24"
      -  key: 256
         value: "ID25 LLCBus Over Current protection"
      -  key: 512
         value: "ID26 Bus over voltage protection"
      -  key: 1024
         value: "ID27 Battery Over Current protection"
      -  key: 2048
         value: "ID28 Dci Over Current Protection"
      -  key: 4096
         value: "ID29 Output over current software"
      -  key: 8192
         value: "ID30 Buck Over Current"
      -  key: 16384
         value: "ID31 Output over current protection"
      -  key: 32768
         value: "ID32"
      icon: 'mdi:wrench'  

    - name: "Alert Fault 3"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0203]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "ID33 Reserved"
      -  key: 2
         value: "ID34 Reserved"
      -  key: 4
         value: "ID35 Reserved"
      -  key: 8
         value: "ID36 Reserved"
      -  key: 16
         value: "ID37 Reserved"
      -  key: 32
         value: "ID38 Reserved"
      -  key: 64
         value: "ID39 Reserved"
      -  key: 128
         value: "ID40 Reserved"
      -  key: 256
         value: "ID41 Reserved"
      -  key: 512
         value: "ID42 Reserved"
      -  key: 1024
         value: "ID43 Reserved"
      -  key: 2048
         value: "ID44 Reserved"
      -  key: 4096
         value: "ID45 Reserved"
      -  key: 8192
         value: "ID46 Reserved"
      -  key: 16384
         value: "ID47 Reserved"
      -  key: 32768
         value: "ID48 Reserved"
      icon: 'mdi:wrench'  

    - name: "Alert Fault 4"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0204]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "ID49 Grid voltage sampling value between master and slave DSP vary widely"
      -  key: 2
         value: "ID50 Grid frequency sampling value between master and slave DSP vary widely"
      -  key: 4
         value: "ID51 DCI sampling value between master and slave DSP vary widely"
      -  key: 8
         value: "ID52 GFCI sampling value between master and slave DSP vary widely"
      -  key: 16
         value: "ID53 Communication failure between master and slave DSP failure"
      -  key: 32
         value: "ID53 Communication failure between slave and communication board"
      -  key: 64
         value: "ID55 Relay fault"
      -  key: 128
         value: "ID56"
      -  key: 256
         value: "ID57 Inverter temp is too high"
      -  key: 512
         value: "ID58 Boost temp is too high"
      -  key: 1024
         value: "ID59 Environment temp is too high"
      -  key: 2048
         value: "ID60"
      -  key: 4096
         value: "ID61 Reserved"
      -  key: 8192
         value: "ID62 Reserved"
      -  key: 16384
         value: "ID63 Reserved"
      -  key: 32768
         value: "ID64 Reserved"
      icon: 'mdi:wrench'  

    - name: "Alert Fault 5"
      class: ""
      state_class: ""      
      uom: ""
      scale: 1
      rule: 1
      registers: [0x0205]
      lookup: 
      -  key: 0
         value: "No error"
      -  key: 1
         value: "ID65 Grid current is too high and causes unrecoverable fault"
      -  key: 2
         value: "ID66 Bus voltage is too high and causes unrecoverable fault"
      -  key: 4
         value: "ID67 EPS Mode Battery Over current,and has cause unrecoverable fault"
      -  key: 8
         value: "ID68"
      -  key: 16
         value: "ID69"
      -  key: 32
         value: "ID70 The Output current is too high,and has cause unrecoverable fault"
      -  key: 64
         value: "ID71"
      -  key: 128
         value: "ID72 Reserved"
      -  key: 256
         value: "ID73 Reserved"
      -  key: 512
         value: "ID74"
      -  key: 1024
         value: "ID75 Error writing from EEPROM"
      -  key: 2048
         value: "ID76 Error reading to EEPROM"
      -  key: 4096
         value: "ID77 Relay fauilure causes unrecoverable fault"
      -  key: 8192
         value: "ID78 Reserved"
      -  key: 16384
         value: "ID79 Reserved"
      -  key: 32768
         value: "ID80 Reserved"
      icon: 'mdi:wrench'
```
