### DISCUSSION TITLE
Sofar_wifikit, hows does one get the battery charge total and discharge total?

### DISCUSSION THREAD

**Discussion by Be11icus** [StephanJoubert/home_assistant_solarman#525] [General]
Trying to setup the Energy dashboard but the Battery totals are missing. 
There is only 1 sensor and this combines the Discharge and Charge but also not a state_class: total_increasing.

Any help would be much appreciated

**Comment by Philippe59710fr** [comment]
Hi Be11icus,

Maybe a bit late, anyway here is a yaml package under hass to do so : 
```
template:
  - sensor:
      # Capteurs de base pour les calculs suivants
      - name: "Solarman charge/discharge power"
        unique_id: solarman_charge_discharge_power
        device_class: power
        unit_of_measurement: kW
        state: >
          {{ (states('sensor.solarman_battery_charge_discharge_power_2') | float(0)) }}
        availability: >
          {{ states('sensor.solarman_battery_charge_discharge_power_2')|is_number }}
      - name: "Solarman PV power"
        unique_id: solarman_pv_power
        device_class: power
        unit_of_measurement: kW
        state: >
          {{ (states('sensor.solarman_generation_power_2') | float(0)) }}
        availability: >
          {{ states('sensor.solarman_generation_power_2')|is_number }}
      - name: "Solarman Home power"
        unique_id: solarman_home_power
        device_class: power
        unit_of_measurement: kW
        state: >
          {{ (states('sensor.solarman_consumption_power_2') | float(0)) }}
        availability: >
          {{ states('sensor.solarman_consumption_power_2')|is_number }}

      - name: "Solarman Grid power"
        unique_id: solarman_grid_power
        device_class: power
        unit_of_measurement: kW
        state: >
          {{ (  states('sensor.solarman_home_power') | float
          +(states('sensor.solarman_charge_discharge_power') | float)
          -(states('sensor.solarman_pv_power') | float)) }}
        availability: >
          {{ states('sensor.solarman_consumption_power_2')|is_number }}

      - name: "Solarman Charge Power"
        unique_id: solarman_charge_power
        device_class: power
        unit_of_measurement: kW
        state: >
          {% set sensor_state = (states('sensor.solarman_battery_charge_discharge_power_2') | float) %}
          {{ sensor_state if sensor_state >= 0 else 0 }}
        availability: >
          {{ states('sensor.solarman_battery_charge_discharge_power_2')|is_number }}
      - name: "Solarman Discharge Power"
        unique_id: solarman_discharge_power
        device_class: power
        unit_of_measurement: kW
        state: >
          {% set sensor_state = (states('sensor.solarman_battery_charge_discharge_power_2') | float) %}
          {{ 0 - sensor_state if sensor_state < 0 else 0 }}
        availability: >
          {{ states('sensor.solarman_battery_charge_discharge_power_2')|is_number }}
      - name: "Solarman computed battery"
        unique_id: solarman_computed_battery
        device_class: battery
        state_class: measurement
        unit_of_measurement: "%"
        icon: mdi:battery
        state: >
          {{ ((states('sensor.solarman_battery_soc_2')|float-20)*1.25) | int }}
      - name: "Solarman computed energy left"
        unique_id: "solarman_computed_energy_left"
        unit_of_measurement: kWh
        device_class: energy
        icon: mdi:battery
        # 8 = 8Kwh batterie utilisable
        state: >
          {{ (states('sensor.solarman_computed_battery')|float*8)/100 }}
      - name: "Solarman computed efficiency"
        unique_id: solarman_computed_efficiency
        device_class: battery
        state_class: measurement
        unit_of_measurement: "%"
        state: >
          {{ ((states('sensor.solarman_discharge_energy')|float)/(states('sensor.solarman_charge_energy')|float)*100)|int }}

sensor:
  - platform: integration
    name: "Solarman charge energy"
    unique_id: solarman_charge_energy
    source: sensor.solarman_charge_power
    unit_time: "h"
    method: "left"
  - platform: integration
    name: "Solarman discharge energy"
    unique_id: solarman_discharge_energy
    source: sensor.solarman_discharge_power
    unit_time: "h"
    method: "left"
```

The computed energy left is based on two 4.8Kwh batteries 
```
        # 8 = 8Kwh batterie utilisable
        state: >
          {{ (states('sensor.solarman_computed_battery')|float*8)/100 }}
```
