### DISCUSSION TITLE
Is it possible to write the registers with Solarman?

### DISCUSSION THREAD

**Discussion by amiko24** [StephanJoubert/home_assistant_solarman#620] [Q&A]
How can I write the registers about Solarman. 
If I change mb_functioncode to 10, Solarman status changes to desconnect.
  - start: 0x0063
    end: 0x006F
    mb_functioncode: 0x10 

I use deye_sg04lp3.yaml

**Comment by joergjanssen** [comment]
.....me too: would be soooo nice to write the "Active Power Regulations" Parameter to set the Power-Transfer !!!

**Comment by amiko24** [comment]
@joergjanssen Which inverters do you have? What percentage do you want to set?

**Reply by joergjanssen** [reply]
...I managed it on my own with this automatisation - It uses a `input_number` as a slider, that sets the Inverter-Output-Power with the service `solarman.write_multiple_holding_registers` by writing the percentage value into register 40 (decimal - 108 hex)  
```
alias: Autom_setMI600
description: ""
trigger:
  - platform: state
    entity_id:
      - input_number.set_mi600
    to: null
condition: []
action:
  - service: solarman.write_multiple_holding_registers
    data:
      register: 40
      values: "{{ states('input_number.set_mi600')|int(0) }}"
mode: single
```
To expalin the idea for this: I have a battery/PowerStation betwenn SolarPanesl and Inverter, and don't want to give all 600W to Inverer if not needed, to save Battery Power

![image](https://github.com/user-attachments/assets/d537d2ee-7ad4-405c-be2e-180ef7b5bde4)

Next Step will be further automatisation of setting Inverter-Power on its own by reading-data of my House-Power-Consumption . . .
