### ISSUE TITLE
Sensors stay in "unknwon" status

### ISSUE THREAD

**Issue by otello86** [StephanJoubert/home_assistant_solarman#114]
Hi,
i try to use this integration with my Sofar HYD-5000ES with wifi logger (S/N: 23XXXXXX). I put on all the parameters and restart HA but all the sensor stay in status “unknown”.
I try different .yaml configuration but the sensors still have unkown status
I don’t have any error message in log and i don't know if the connection to the datalogger works or not
I also try autodiscover mode but without success

The integration is in version 1.4.1
HA works HA OS in version 2022.10.2

**Comment by Magno06** [comment]
Same problem. I still don't know how to fix

**Comment by kkapuscinski** [comment]
Hi, same here but i have Sofar 8.8 KTLX-G3. for now i see that different port gives "Connection refused" and 8899 stalls for 40 seconds.

**Comment by vegahansen** [comment]
I have the same issue. Afore inverter with Solarman logger. Able to log in on the IP adress, hacks reports connected but no values on the sensors in HA. Logger SN 17xxxxxx

**Comment by s0x00c** [comment]
Another ME3000SP here. 
Device serial 23xxxx
Telnet connection can be made on port 8899 from the home assistant cli interface.
40 entities are created but I don't seem to be able to gather data.
Willing to test if wanted / needed.

**Comment by s0x00c** [comment]
@mcasteels : there is a sofar_wfikit.yaml file included when you clone the repo
I removed the solarman integration completely and then redownloaded it again.
This time, before adding it to the interface, I copied the sofar_wifikit.yaml over the sofar_lsw3.yaml and then proceeded by adding the integration again.
It seems to read some data now from my inverter seeing this in the logbook:
![image](https://user-images.githubusercontent.com/91124858/211173512-f89d53b6-bd98-4637-8292-d292d792a104.png)
Then I can click through and see the state of the battery charge during the full last day, meaning it connected and read historic data:
![image](https://user-images.githubusercontent.com/91124858/211173543-609fa916-f504-4de9-9b28-02855197cbf5.png)
Right now, I added the counters to the battery dashboard but they don't seem to update yet anyway.
I am seeing this as good news, seems there is a possibility to read the data of the inverter while all other have failed for me.

**Comment by mcasteels** [comment]
@s0x00c ,

Thanks for that great info.  I was using the HACS integration and that is different than the one on the site!  I always assumed that these are the same. 
I had first some issues but ended up doing the following and that was a win.  No shortcuts, tried it and ended up to be more work.  So really step by step (again thanks to your info)

1. Remove the integration from HA.
2. Restart HA
3. Remove the integration from HACS (did not do that before and this is also a crucial step, I copied it over the existing before, did not work!).  Verify the custom_components folder that the Solarman folder is deleted.
4. Restart HA
5. Download the GitHub repository (clone) and place it in custom_components
6. Rename the file as you did (you could choose the wifi yaml, but who cares, I did not want to test anymore 😬)
7. Restart HA
8. Add the integration fill in the correct info (it adds 51 entities)

I can see the logbook entries and connection is made and noticed some updates (SN, software version, …).  Verified entity by entity and I do see info.  No more unknowns for the moment.  Still need to verify the data versus the API.  Looks promising.

Before I had several issues trying your solution.  What changed it in the end … Delete all the Solarman integrations (HA and HACS! I also had a disabled one) and restarted after each change and not accumulate to only restart once.

**Comment by s0x00c** [comment]
@mcasteels 
Do you have a possibility to add to the energy dashboard?
I see this link: https://github.com/StephanJoubert/home_assistant_solarman/blob/main/energy.md but that definition is not in the sofar_wifikit.yaml.
Would it be possible just to copy those entries over and see if they pick up anything?

**Comment by s0x00c** [comment]
Well, I tried that, but copying in the definitions from another yaml config file doesn't work.
We would need the exact modbus "addresses" to read the correct values.

**Comment by mcasteels** [comment]
> @mcasteels Do you have a possibility to add to the energy dashboard? I see this link: https://github.com/StephanJoubert/home_assistant_solarman/blob/main/energy.md but that definition is not in the sofar_wifikit.yaml. Would it be possible just to copy those entries over and see if they pick up anything?

I was able to add entries to the Energy Dashboard, but really limited and I think that the ones I could add (daily solar panel) will not add anything useful.  I can't add the battery system.

**Comment by mcasteels** [comment]
> Well, I tried that, but copying in the definitions from another yaml config file doesn't work. We would need the exact modbus "addresses" to read the correct values.

that is what I tried before and nothing helped.  the only way I could get it working now is thanks to your info.  To be honest I even did not test the sofar_lsw3.yaml.  I just used the sofar_wifikit.yaml but renamed it to the sofar_lsw3.yaml and point to that one when setting up the integration.  Seems that these SOFAR's are not always defined in the same way.  Mine is just used for the battery system and has sensors too look at my solar panel system (that was already installed +10 years ago).  The battery was installed 2 months ago.

**Comment by s0x00c** [comment]
> > Well, I tried that, but copying in the definitions from another yaml config file doesn't work. We would need the exact modbus "addresses" to read the correct values.
> 
> that is what I tried before and nothing helped. the only way I could get it working now is thanks to your info. To be honest I even did not test the sofar_lsw3.yaml. I just used the sofar_wifikit.yaml but renamed it to the sofar_lsw3.yaml and point to that one when setting up the integration. Seems that these SOFAR's are not always defined in the same way. Mine is just used for the battery system and has sensors too look at my solar panel system (that was already installed +10 years ago). The battery was installed 2 months ago.

Same here, I would like to see the battery integrated in the 'energy dashboard'.
The funny thing is, I can actually see  the battery charging / discharging graphic, but no way to add it to the energy dashboard in separate counters
![image](https://user-images.githubusercontent.com/91124858/211313295-8b6d1c14-2b7a-4811-977d-091e81e81081.png)

**Comment by mcasteels** [comment]
Same thing here.

**Comment by vegahansen** [comment]
> Well, I tried that, but copying in the definitions from another yaml config file doesn't work. We would need the exact modbus "addresses" to read the correct values.

Yes, I think this is also my issue. Currently I have no information on the adress list for my setup with AFORE inverter. Can't find this anywhere.

**Comment by s0x00c** [comment]
@mcasteels 
So, eventually I found the solution:
We needed to split up the charge / discharge counter with a riemann calculation: (in the configuration.yaml file)

```
template:
  - sensor:
    - name: "Battery Charge Power"
      state_class: "measurement"
      device_class: "power"
      unit_of_measurement: "kW"
      icon: mdi:battery-plus
      state: >-
        {% set e = states('sensor.solarman_battery_charge_discharge_power') %}
        {{ e|float(0)|abs if e|float(0) >= 0 else 0 }}
      availability: >-
        {{ states('sensor.solarman_battery_charge_discharge_power')|is_number }}
    - name: "Battery Discharge Power"
      state_class: "measurement"
      device_class: "power"
      unit_of_measurement: "kW"
      icon: mdi:battery-minus
      state: >-
        {% set e = states('sensor.solarman_battery_charge_discharge_power') %}
        {{ e|float(0)|abs if e|float(0) <= 0 else 0 }}
      availability: >-
        {{ states('sensor.solarman_battery_charge_discharge_power')|is_number }}
```
and get that data then in the energy dashboard with adding this to the configuration.yaml file

```
sensor:
  - platform: integration
    source: sensor.battery_charge_power
    name: battery_charge_energy
    round: 2
  - platform: integration
    source: sensor.battery_discharge_power
    name: battery_discharge_energy
    round: 2
```
This gives you everything you need to get the data in the energy dashboard
