### ISSUE TITLE
Help to create parameters file for "ErgoCell" hybrid inverter

### ISSUE THREAD

**Issue by fergalish** [StephanJoubert/home_assistant_solarman#117]
Hi, this HA integration does not work out-of-the-box for me, and I expect it's because I have this brand of inverter - it seems to be an own-brand for a solar PV installer in Ireland and very difficult to find info online.  So my first question is - does anyone else have this brand of inverter "Ergocell"?

Anyway, to be brief, using the "register_scan.py" python script from pysolarmnanv5 and with a lot of fiddling about and thinking on the results, I have a table of what I believe are input_registers and their corresponding meaning.

e.g. register 3109 corresponds to the daily purchased energy measured in units of 0.1 kWh.  In total I have identified 56 input registers with good confidence and another about 110 unidentified but which return a non-zero value. Many of these 110 seem to never change.

I've also identified 38 holding registers, but their values also don't change and I've not yet figured out what any of those might be.

So now I'd like to create the yaml parameters file for the inverter and I'm starting with the following to extract PV1 Voltage on register 3000.

```
requests:
  - start: 0x0BB0
    end: 0x0BC0
    mb_functioncode: 0x03

parameters:
 - group: solar
   items:
    - name: "PV1 Voltage"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0BB8]
      icon: 'mdi:solar-power'
```

The outcome is that this particular entity has value "Unknown" in HA and all other solarman entities have value "Unavailable". So I guess I'm doing something right, but not enough.

Thanks for any help.
