### ISSUE TITLE
Sunsynk vs DEYE sensors

### ISSUE THREAD

**Issue by hyarionh** [StephanJoubert/home_assistant_solarman#12]
It appears there's a few slight variations in the values returned from a SunSynk inverter vs a Deye.

e.g. I had to disable "Battery Status" and "Grid Status" as these did not work for my 5kW Sunsynk inverter.

Would it be worth adding a flag for parameters and the config to support specifying which Inverter configuration to use?

e.g. something like:
```
sensor:
  - platform: solarman
    name: SunSynk
    inverter_type: sunsynk    
```
