### ISSUE TITLE
Exclude 0 °C for temperature

### ISSUE THREAD

**Issue by hajo62** [StephanJoubert/home_assistant_solarman#156]
Hi have downloaded the actual (Dec. 20.) git repo and copied to my Homeassistant.

Has the _old_ `invalid: 0.0` mechanism been removed in the[ last changes](https://github.com/StephanJoubert/home_assistant_solarman/commit/7143061cf670077bb0b73020ef38c6023945ee4b#diff-9237befa134dfa14257e7cc8e13e4c88193693f1b9b42ce50045a2fe2409ec5e)?

I wonder, how I would exclude the 0 °C reported every morning, when the inverter wakes up?

I have tried with the 
```
      validation: 
        min: 0.1
        invalide_all:
```
for Total Production, but that hadn't invalidated the temperature and I saw the -10 °C in the morning.
And here my temperature definition:
```
    - name: "Radiator temperature"    
      class: "temperature"    
      state_class: "measurement"    
      uom: "°C"    
      scale: 0.01  
      offset: 1000  
      rule: 1    
      registers: [0x005A]    
      icon: "mdi:thermometer"
      validation: 
        min: 0.0
```
