### ISSUE TITLE
Totals are not available in energy grid for sofar_hyd3k-6k.yaml

### ISSUE THREAD

**Issue by murraythegoz** [StephanJoubert/home_assistant_solarman#162]
I just installed the integration but although I can see the single sensors, the "totals" are not made available on Energy config when setting consumption and return.
Only "today" params are available

tried to change the state class to "total_increasing" instead of "total" and reinstanced the component and integration, but with no success.

Any hint?

**Comment by mrwolfjunior** [comment]
> I just installed the integration but although I can see the single sensors, the "totals" are not made available on Energy config when setting consumption and return. Only "today" params are available
> 
> tried to change the state class to "total_increasing" instead of "total" and reinstanced the component and integration, but with no success.
> 
> Any hint?

Hi,

I'm not able to test it right now, but if you add this template to your configuration.yaml, should fix the issue:


```
template:
  - sensor:
      - name: "Prelievo Totale"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.zcs_total_grid_consumption') | float (0) }}"
        availability: "{{ states('sensor.zcs_total_grid_consumption')|is_number }}"
        state_class: total_increasing
        device_class: energy
        icon: mdi:transmission-tower
      - name: "Immissione Totale"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.zcs_total_grid_return') | float(0) }}"
        availability: "{{ states('sensor.zcs_total_grid_return')|is_number }}"
        state_class: total_increasing
        device_class: energy
        icon: mdi:transmission-tower-export
      - name: "Scarica Totale"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.zcs_battery_total_energy_dischaged') | float(0) }}"
        availability: "{{ states('sensor.zcs_battery_total_energy_dischaged')|is_number }}"
        state_class: total_increasing
        device_class: energy
        icon: mdi:battery-low
      - name: "Carica Totale"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.zcs_battery_total_energy_charged') | float(0) }}"
        availability: "{{ states('sensor.zcs_battery_total_energy_charged')|is_number }}"
        state_class: total_increasing
        device_class: energy
        icon: mdi:battery-high
      - name: "Produzione Totale"
        unit_of_measurement: "kWh"
        state: "{{ states('sensor.zcs_total_production') | float(0) }}"
        availability: "{{ states('sensor.zcs_total_production')|is_number }}"
        state_class: total_increasing
        device_class: energy
        icon: mdi:weather-sunny

```

Make sure to change the sensor name inside the "state" and "availability" attributes... Let me know!
