### ISSUE TITLE
SOFAR over ethernet?

### ISSUE THREAD

**Issue by dsgepers** [StephanJoubert/home_assistant_solarman#27]
I have a SOFAR 4KTLM-G2. However I'm not connected over WiFi but over wired ethernet. For the whole rest I have access to the whole admin screen and see my IP, serial number etc... 

I've also tried following along with the solution offered in #18, but it didn't help my situation. I also went looking around in the logs, but I can't seem to find request logs or something to confirm wether or not requests are attempted or as to why they're failing.

![image](https://user-images.githubusercontent.com/4004850/159115434-cba6e444-6929-4c87-89f6-5323882d73c0.png)

However I'm only getting as "disconnected" status in HA. 

I'm using the following config in my configuration.yaml:
```
sensor:
  - platform: solarman
    name: SOFAR
    inverter_host: 192.168.0.183
    inverter_port: 8899
    inverter_serial: 2103705955
    scan_interval: 30
    lookup_file: sofar_lsw3.yaml
``` 

However the status remains disconnected and no data is coming in:
![image](https://user-images.githubusercontent.com/4004850/159115504-3ad5b2c4-9c23-412e-8aae-2ae183aa32c1.png)

![image](https://user-images.githubusercontent.com/4004850/159115512-15bed393-2d44-4c63-a0da-4bdf5b435c8e.png)

Can you shed any light on my predicament? :-)
