### ISSUE TITLE
Deye SUN 800 - Power per MPPT

### ISSUE THREAD

**Issue by WouterJN** [StephanJoubert/home_assistant_solarman#276]
In the solar man application I can see the power (Watt) per MPPT for my SUN800G3. This information is not shown in Home Assistant. Could power per MPPT be added?

**Comment by DHLF** [comment]
The SUN800G3 with two mppt transmits total power(watts) for BOTH(PV1+PV2) combined.
As the data for each PV module is given in amps and voltage you can calculate it for yourself by multiplying both values:
{{ states('sensor.deye_pv1_voltage') | float * states('sensor.deye_pv1_current') | float }}
{{ states('sensor.deye_pv2_voltage') | float * states('sensor.deye_pv2_current') | float }}
and of course for those with 4 mppts:
{{ states('sensor.deye_pv3_voltage') | float * states('sensor.deye_pv3_current') | float }}
{{ states('sensor.deye_pv4_voltage') | float * states('sensor.deye_pv4_current') | float }}

You have to change the naming for your setup so instead of deye_ you have to use whatever you typed when installing.

I am looking for a proper solution for the 4mppt(2000G3) myself.. as this may be the proper calculation but hence.. i am unable to create new "identities" like deye_pv1_power YET.
Putting this stuff in the configuration.yaml did not help as the new "identities" cant be seen anywhere -.-

```
solarman:
  - platform: template
    sensors:
      deye_pv1_power:
      unit_of_measurement: W
      device_class: power
      value_template: {{ states('sensor.deye_pv1_voltage') | float * states('sensor.deye_pv1_current') | float }}
```

**Comment by DHLF** [comment]
Crawling around I *may* have found a solution:
Putting this into the /config/configuration.yaml:
```
template:
  - sensor:
      - name: deye_2k_pv1_wattz
        unit_of_measurement: "W"
        state: "{{ (states('sensor.deye_2k_pv1_voltage') | float) * (states('sensor.deye_2k_pv1_current') | float) }}"
        icon: "mdi:solar-power-variant-outline"
      - name: deye_2k_pv2_wattz
        unit_of_measurement: "W"
        state: "{{ (states('sensor.deye_2k_pv2_voltage') | float) * (states('sensor.deye_2k_pv2_current') | float) }}"
        icon: "mdi:solar-power-variant-outline"
      - name: deye_2k_pv3_wattz
        unit_of_measurement: "W"
        state: "{{ (states('sensor.deye_2k_pv3_voltage') | float) * (states('sensor.deye_2k_pv3_current') | float) }}"
        icon: "mdi:solar-power-variant-outline"
      - name: deye_2k_pv4_wattz
        unit_of_measurement: "W"
        state: "{{ (states('sensor.deye_2k_pv4_voltage') | float) * (states('sensor.deye_2k_pv4_current') | float) }}"
        icon: "mdi:solar-power-variant-outline"
```
The **-name: deye_2k_pv1_wattz** will be the entity name which should be usable in HA. You may change it like you wish, this example is my definition to divert between different installed microinverters.

If you installed solarman WITHOUT changing the prefix the "states" will be known as "sensor.**solarman**_pv1_voltage" and "sensor.**solarman**_pv1_current". Change it to your setup.

Some things to keep in mind:
1.) you MUST restart HA. Just changing the configuration.yaml will do nothing otherwise..
2.) If the sun is down so the values are not valid and.. error will be shown as the value "undefined" is no float :D 
 You may use a conditional Card using **sensor_solarman_status_connection** comparing to **connected** to hide error cards.
3.) If you got only 2mppts dont use the last two entries as the entities will not be found and error will be shown -.-

Disclaimer: I have not yet tested this because its dark outside now -.- But its the first time HA accepted this stuff in the configuration :)
