### ISSUE TITLE
deye_2mppt.yaml is missing net current

### ISSUE THREAD

**Issue by DHLF** [StephanJoubert/home_assistant_solarman#286]
Thank you for the new temperature sensors ;)

During reinstallation i could not find the (earlier accessible entity) net-current.

Comparing both the deye_2mppt.yaml and the deye_4mppt.yaml it seems the part about "Grid Current" was missing.
If deye_2mppt.yaml is patched ike this(borrowing the part from deye_4mppt.yaml):

```
  - group: Grid
    items:
    - name: "AC Voltage"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0049]
      icon: 'mdi:transmission-tower'

    - name: "Grid Current"
      class: "current"
      state_class: "measurement"
      uom: "A"
      scale: 0.1
      rule: 2
      registers: [0x004C]
      icon: 'mdi:home-lightning-bolt'

    - name: "AC Output Frequency"
      class: "frequency"
      state_class: "measurement"
      uom: "Hz"
      scale: 0.01
      rule: 1
      registers: [0x004F]
      icon: 'mdi:home-lightning-bolt'
```
It works as expected :)
