### ISSUE TITLE
More inverters

### ISSUE THREAD

**Issue by carstenit** [StephanJoubert/home_assistant_solarman#300]
I cannot get it to work with more than one inverter,  i believe it could be a json error - dublicate key “name" or something like that?

**Comment by DHLF** [comment]
To add another inverter you MUST add another solarman integration.
DONT change the (first) one you got already running! Any change there will "drop" the first inverter and add the second!

Instead click on the gear(spiked circle) on the left(Configuration/Settings?)
The next page should be the one with all already found integrations like "sun", your solarman ..
Click the button in the lower right "add integration" and select AGAIN solarman.
Configure this to your needs.

Strange description due to other language settings. sorry.

**Comment by DHLF** [comment]
I got a master-slave configuration working(mixed 600+2000).. where the 600 as first and the 2000 as last device in the "string" so output of the 2000 would went into the net.
*may NOT be as intended by manufacturer(mixing microinverters of different types) * so dont try this!!
I did NOT change the inverter slave ids.. so they stayed both at 1.

In this configuration both showed up with different "prefixes" in the entity names.

---
Things you may try:
If you mistyped the inverter_serial in the HA config/solarman it will NEVER be able to connect therefore unknown values so doublecheck this.
MAYBE it is right to switch the slave id to 2 but as stated above it worked without changing this parameter

**Comment by NikiSkaarup** [comment]
I finally got my second inverter working after some trial and error

So in order to get more than 1 inverter to work I had to make a copy of `deye_sg04lp3.yaml` as `deye_sg04lp3_no_bat.yaml` file and for the secondary inverter and add it in the `const.py` file so I could select it

in the `deye_sg04lp3_no_bat.yaml` file find
```yaml
      - name: "Battery Temperature"
        class: "temperature"
        state_class: "measurement"
        uom: "°C"
        scale: 0.1
        rule: 1
        offset: 1000
        registers: [0x024A]
        icon: "mdi:battery"
        validation:
          min: 1
          max: 99
          invalidate_all:
```
and remove
```yaml
        validation:
          min: 1
          max: 99
          invalidate_all:
```

since my second inverter isn't connected directly to the batteries, it reports battery temp as -100, so it failed the validation and invalidated all fields
