### ISSUE TITLE
Bluesun.yaml

### ISSUE THREAD

**Issue by sven0833** [StephanJoubert/home_assistant_solarman#330]
can some one do a bluesun.yaml for bluesun inverter, all the .yaml file ive tested and all say disconnected

**Comment by giedriuskilcauskas** [comment]
[Inverter Modbus Communication  Protocol 2.2(1).pdf](https://github.com/StephanJoubert/home_assistant_solarman/files/14569794/Inverter.Modbus.Communication.Protocol.2.2.1.pdf)
This is registry map. I was able to get values using pysolarmanv5 python directly, but so far integration doesn't work.

this is my current try of definition:
```yaml
requests:
  - start: 2964
    end: 3139
    mb_functioncode: 0x04
  - start: 3200
    end: 3230
    mb_functioncode: 0x03
  - start: 3300
    end: 3340
    mb_functioncode: 0x10
  - start: 4000
    end: 4046
    mb_functioncode: 0x06

parameters:
  - group: Inverter
    items:
      # - name: "Working Mode"
      #   class: ""
      #   state_class: ""
      #   uom: ""
      #   scale: 1
      #   rule: 1
      #   registers: [3040]
      #   icon: 'mdi:home-lightning-bolt'
      #   lookup:
      #       - key: 0
      #         value: "No response mode"
      #       - key: 1
      #         value: "Volt–watt default"
      #       - key: 2
      #         value: "Volt–var"
      #       - key: 3
      #         value: "Fixed power factor"
      #       - key: 4
      #         value: "Fix reactive power"
      #       - key: 5
      #         value: "Power-PF"
      #       - key: 6
      #         value: "Rule21Volt–watt"

      # - name: "Grid status"
      #   class: ""
      #   state_class: ""
      #   uom: ""
      #   scale: 1
      #   rule: 1
      #   registers: [4999]
      #   icon: 'mdi:home-lightning-bolt'

      - name: "Inverter Temperature"
        class: "temperature"
        state_class: "measurement"
        uom: "°C"
        scale: 0.1
        rule: 2
        registers: [3025]
        icon: "mdi:thermometer"

      - name: "Product Model"
        class: ""
        state_class: ""
        uom: ""
        scale: 1
        rule: 5
        registers: [3228, 3227, 3226, 3225, 3224, 3223, 3222, 3221]
        isstr: true

      - name: "DSP Software Version"
        class: ""
        state_class: ""
        uom: ""
        scale: 1
        rule: 1
        registers: [3205]
        isstr: true

      - name: "LCD Software Version"
        class: ""
        state_class: ""
        uom: ""
        scale: 1
        rule: 1
        registers: [3332]
        isstr: true

      # - name: "Inverter Status"
      #   class: ""
      #   state_class: ""
      #   uom: ""
      #   scale: 1
      #   rule: 1
      #   registers: [3043]
      #   icon: "mdi:list-status"
      #   isstr: true
      #   lookup:
      #     - key: 0
      #       value: "Waiting"
      #     - key: 1
      #       value: "OpenRun"
      #     - key: 2
      #       value: "SoftRun"
      #     - key: 3
      #       value: "Generating"
      #     - key: 1004
      #       value: "Grid off"
      #     - key: 2011
      #       value: "Fail Safe"

  - group: InverterDC
    items:
      - name: "DC Voltage 1"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [3000]
        icon: "mdi:solar-power"

      - name: "DC Voltage 2"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [3001]
        icon: "mdi:solar-power"

      - name: "DC Current 1"
        class: "current"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [3003]
        icon: "mdi:current-dc"

      - name: "DC Current 2"
        class: "current"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [3004]
        icon: "mdi:current-dc"

      - name: "DC Power 1"
        class: "power"
        state_class: "measurement"
        uom: "kW"
        scale: 0.001
        rule: 4
        registers: [3007, 3006]
        icon: "mdi:solar-power"

      - name: "DC Power 2"
        class: "power"
        state_class: "measurement"
        uom: "kW"
        scale: 0.001
        rule: 4
        registers: [3009, 3008]
        icon: "mdi:solar-power"

  - group: InverterAC
    items:
      # - name: "Active power"
      #   class: "power"
      #   state_class: "measurement"
      #   uom: "kW"
      #   scale: 0.001
      #   rule: 3
      #   registers: [3005, 3004]
      #   icon: 'mdi:solar-power'

      - name: "Inverter AC Power"
        class: "power"
        state_class: "measurement"
        uom: "kW"
        scale: 0.001
        rule: 4
        registers: [3024, 3023]
        icon: "mdi:solar-power"

      - name: "A phase voltage"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [3014]
        icon: "mdi:transmission-tower"

      - name: "B phase voltage"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [3015]
        icon: "mdi:transmission-tower"

      - name: "C phase voltage"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [3016]
        icon: "mdi:transmission-tower"

      - name: "A phase current"
        class: "current"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [3020]
        icon: "mdi:current-ac"

      - name: "B phase current"
        class: "current"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [3021]
        icon: "mdi:current-ac"

      - name: "C phase current"
        class: "current"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [3022]
        icon: "mdi:current-ac"

      - name: "A phase Frequency"
        class: "frequency"
        state_class: "measurement"
        uom: "Hz"
        scale: 0.01
        rule: 1
        registers: [3017]
        icon: "mdi:sine-wave"

      - name: "B phase Frequency"
        class: "frequency"
        state_class: "measurement"
        uom: "Hz"
        scale: 0.01
        rule: 1
        registers: [3018]
        icon: "mdi:sine-wave"

      - name: "C phase Frequency"
        class: "frequency"
        state_class: "measurement"
        uom: "Hz"
        scale: 0.01
        rule: 1
        registers: [3019]
        icon: "mdi:sine-wave"

  - group: Generation
    items:
      - name: "Daily Generation"
        class: "energy"
        state_class: "measurement"
        uom: "kWh"
        scale: 1
        rule: 1
        registers: [3042]
        icon: "mdi:solar-power"

      - name: "Monthly Generation"
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        scale: 1
        rule: 3
        registers: [3103, 3102]
        icon: "mdi:solar-power"

      - name: "Yearly Generation"
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        scale: 1
        rule: 3
        registers: [3041, 3040]
        icon: "mdi:solar-power"

      - name: "Total Generation"
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        scale: 0.1
        rule: 3
        registers: [3039, 3038]
        icon: "mdi:solar-power"
```

**Comment by demand187** [comment]
Have you managed to get it to work in the meantime?

**Comment by giedriuskilcauskas** [comment]
> Have you managed to get it to work in the meantime?

@demand187 , I did, here is my custom_parameters.yaml file:
```
# BlueSun BSM10k
#
requests:
  - start: 3000
    end: 3020
    mb_functioncode: 0x04
  - start: 3021
    end: 3042
    mb_functioncode: 0x04


parameters:
  - group: Inverter
    items:
      # - name: "Working Mode"
      #   class: ""
      #   state_class: ""
      #   uom: ""
      #   scale: 1
      #   rule: 1
      #   registers: [3040]
      #   icon: 'mdi:home-lightning-bolt'
      #   lookup:
      #       - key: 0
      #         value: "No response mode"
      #       - key: 1
      #         value: "Volt–watt default"
      #       - key: 2
      #         value: "Volt–var"
      #       - key: 3
      #         value: "Fixed power factor"
      #       - key: 4
      #         value: "Fix reactive power"
      #       - key: 5
      #         value: "Power-PF"
      #       - key: 6
      #         value: "Rule21Volt–watt"

      # - name: "Grid status"
      #   class: ""
      #   state_class: ""
      #   uom: ""
      #   scale: 1
      #   rule: 1
      #   registers: [4999]
      #   icon: 'mdi:home-lightning-bolt'

      - name: "Inverter Temperature"
        class: "temperature"
        state_class: "measurement"
        uom: "°C"
        scale: 0.1
        rule: 2
        registers: [3025]
        icon: "mdi:thermometer"

      # - name: "Product Model"
      #   class: ""
      #   state_class: ""
      #   uom: ""
      #   scale: 1
      #   rule: 5
      #   registers: [3228, 3227, 3226, 3225, 3224, 3223, 3222, 3221]
      #   isstr: true

      # - name: "DSP Software Version"
      #   class: ""
      #   state_class: ""
      #   uom: ""
      #   scale: 1
      #   rule: 1
      #   registers: [3205]
      #   isstr: true

      # - name: "LCD Software Version"
      #   class: ""
      #   state_class: ""
      #   uom: ""
      #   scale: 1
      #   rule: 1
      #   registers: [3332]
      #   isstr: true

      # - name: "Inverter Status"
      #   class: ""
      #   state_class: ""
      #   uom: ""
      #   scale: 1
      #   rule: 1
      #   registers: [3043]
      #   icon: "mdi:list-status"
      #   isstr: true
      #   lookup:
      #     - key: 0
      #       value: "Waiting"
      #     - key: 1
      #       value: "OpenRun"
      #     - key: 2
      #       value: "SoftRun"
      #     - key: 3
      #       value: "Generating"
      #     - key: 1004
      #       value: "Grid off"
      #     - key: 2011
      #       value: "Fail Safe"

  - group: InverterDC
    items:
      - name: "DC Voltage 1"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [3000]
        icon: "mdi:solar-power"

      - name: "DC Voltage 2"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [3001]
        icon: "mdi:solar-power"

      - name: "DC Current 1"
        class: "current"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [3003]
        icon: "mdi:current-dc"

      - name: "DC Current 2"
        class: "current"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [3004]
        icon: "mdi:current-dc"

      - name: "DC Power 1"
        class: "power"
        state_class: "measurement"
        uom: "kW"
        scale: 0.001
        rule: 4
        registers: [3007, 3006]
        icon: "mdi:solar-power"

      - name: "DC Power 2"
        class: "power"
        state_class: "measurement"
        uom: "kW"
        scale: 0.001
        rule: 4
        registers: [3009, 3008]
        icon: "mdi:solar-power"

  - group: InverterAC
    items:
      # - name: "Active power"
      #   class: "power"
      #   state_class: "measurement"
      #   uom: "kW"
      #   scale: 0.001
      #   rule: 3
      #   registers: [3005, 3004]
      #   icon: 'mdi:solar-power'

      - name: "Inverter AC Power"
        class: "power"
        state_class: "measurement"
        uom: "kW"
        scale: 0.001
        rule: 4
        registers: [3024, 3023]
        icon: "mdi:solar-power"

      - name: "A phase voltage"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [3014]
        icon: "mdi:transmission-tower"

      - name: "B phase voltage"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [3015]
        icon: "mdi:transmission-tower"

      - name: "C phase voltage"
        class: "voltage"
        state_class: "measurement"
        uom: "V"
        scale: 0.1
        rule: 1
        registers: [3016]
        icon: "mdi:transmission-tower"

      - name: "A phase current"
        class: "current"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [3020]
        icon: "mdi:current-ac"

      - name: "B phase current"
        class: "current"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [3021]
        icon: "mdi:current-ac"

      - name: "C phase current"
        class: "current"
        state_class: "measurement"
        uom: "A"
        scale: 0.1
        rule: 1
        registers: [3022]
        icon: "mdi:current-ac"

      - name: "A phase Frequency"
        class: "frequency"
        state_class: "measurement"
        uom: "Hz"
        scale: 0.01
        rule: 1
        registers: [3017]
        icon: "mdi:sine-wave"

      - name: "B phase Frequency"
        class: "frequency"
        state_class: "measurement"
        uom: "Hz"
        scale: 0.01
        rule: 1
        registers: [3018]
        icon: "mdi:sine-wave"

      - name: "C phase Frequency"
        class: "frequency"
        state_class: "measurement"
        uom: "Hz"
        scale: 0.01
        rule: 1
        registers: [3019]
        icon: "mdi:sine-wave"

  - group: Generation
    items:
      - name: "Daily Generation"
        class: "energy"
        state_class: "measurement"
        uom: "kWh"
        scale: 1
        rule: 1
        registers: [3042]
        icon: "mdi:solar-power"

      # - name: "Monthly Generation"
      #   class: "energy"
      #   state_class: "total_increasing"
      #   uom: "kWh"
      #   scale: 1
      #   rule: 3
      #   registers: [3103, 3102]
      #   icon: "mdi:solar-power"

      - name: "Yearly Generation"
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        scale: 1
        rule: 3
        registers: [3041, 3040]
        icon: "mdi:solar-power"

      - name: "Total Generation"
        class: "energy"
        state_class: "total_increasing"
        uom: "kWh"
        scale: 0.1
        rule: 3
        registers: [3039, 3038]
        icon: "mdi:solar-power"
```
