### ISSUE TITLE
Invalid "Operating Status" in Solis Hybrid definition

### ISSUE THREAD

**Issue by Kdceddj** [StephanJoubert/home_assistant_solarman#404]
In the [Solis Modbus spec](https://www.scss.tcd.ie/Brian.Coghlan/Elios4you/RS485_MODBUS-Hybrid-BACoghlan-201811228-1854.pdf), Operating Status (Working Status) is defined as follows:
![image](https://github.com/StephanJoubert/home_assistant_solarman/assets/93988650/8176b551-ef3e-48b5-b49d-7f8014a2f183)

However, the lookup in the solis_hybrid.yaml seems to be incorrect:
``` yaml
      lookup:
      -  key: 0x701
         value: "Normal Operation"
      -  key: 0x702
         value: "Initial Standby"
      -  key: 0x704
         value: "Control Shutdown"
      -  key: 0x708
         value: "Downtime"
      -  key: 0x710
         value: "Standby"
      -  key: 0x720
         value: "Derating Operation"
      -  key: 0x740
         value: "Limit Operation"
      -  key: 0x780
         value: "Bypass Overload"
```

In my case, Operating Status shows a value of 8 in HA, while it should show one of the text values from the above lookup.
