### ISSUE TITLE
Additional registers

### ISSUE THREAD

**Issue by markodraca** [StephanJoubert/home_assistant_solarman#427]
Hi

I've edited deye_sg04lp3.yaml so its compatible with https://github.com/slipx06/sunsynk-power-flow-card
Basically, just added some registers. If anyone is interested, I can push the script.

**Comment by Sorentino1964** [comment]
Super, dass wäre nett wenn du das hier einstellen würdest.
Great, it would be nice if you would post it here

**Comment by markodraca** [comment]
Sure

[deye_sg04lp3.zip](https://github.com/StephanJoubert/home_assistant_solarman/files/13060827/deye_sg04lp3.zip)

HA power flow card configuration

```
- type: custom:sunsynk-power-flow-card
        cardstyle: full
        panel_mode: true
        show_solar: true
        inverter:
          modern: true
          autarky: power
          three_phase: true
        battery:
          energy: 16000
          shutdown_soc: 5
          show_daily: true
          invert_power: false
          max_power: 12000
          full_capacity: 95
          empty_capacity: 10
          colour: limegreen
        solar:
          show_daily: true
          mppts: 2
          max_power: 8700
          pv1_name: Istok
          pv2_name: Zapad
        load:
          show_daily: true
          max_power: 12000
        grid:
          show_daily_buy: true
          show_daily_sell: true
          show_nonessential: true
          nonessential_name: Sanitarna
          nonessential_icon: mdi:water-boiler
          max_power: 6000
        entities:
          use_timer_248: 'no'
          priority_load_243: 'no'
          day_battery_charge_70: sensor.solarman_daily_battery_charge
          day_battery_discharge_71: sensor.solarman_daily_battery_discharge
          day_load_energy_84: sensor.solarman_daily_load_consumption
          day_grid_import_76: sensor.solarman_daily_energy_bought
          day_grid_export_77: sensor.solarman_daily_energy_sold
          day_pv_energy_108: sensor.solarman_daily_production
          pv1_power_186: sensor.solarman_pv1_power
          pv2_power_187: sensor.solarman_pv2_power
          battery_voltage_183: sensor.solarman_battery_voltage
          battery_soc_184: sensor.solarman_battery_soc
          battery_power_190: sensor.solarman_battery_power
          battery_current_191: sensor.solarman_battery_current
          pv1_voltage_109: sensor.solarman_pv1_voltage
          pv1_current_110: sensor.solarman_pv1_current
          pv2_voltage_111: sensor.solarman_pv2_voltage
          pv2_current_112: sensor.solarman_pv2_current
          inverter_status_59: sensor.solarman_alert
          remaining_solar: sensor.energy_production_today_remaining
          dc_transformer_temp_90: sensor.solarman_dc_temperature
          radiator_temp_91: sensor.solarman_ac_temperature
          load_frequency_192: sensor.solarman_grid_frequency
          inverter_voltage_154: sensor.solarman_grid_voltage_l1
          inverter_voltage_L2: sensor.solarman_grid_voltage_l2
          inverter_voltage_L3: sensor.solarman_grid_voltage_l3
          inverter_current_164: sensor.solarman_current_l1
          inverter_current_L2: sensor.solarman_current_l2
          inverter_current_L3: sensor.solarman_current_l3
          load_power_L1: sensor.solarman_load_l1_power
          load_power_L2: sensor.solarman_load_l2_power
          load_power_L3: sensor.solarman_load_l3_power
          grid_ct_power_L2: sensor.solarman_external_ct_l2_power
          grid_ct_power_L3: sensor.solarman_external_ct_l3_power
          essential_power: sensor.solarman_essential_total_load_power
          inverter_power_175: sensor.solarman_total_load_power
          grid_power_169: sensor.solarman_internal_ct_total_power
          grid_ct_power_172: sensor.solarman_external_ct_total_power
          nonessential_power: none
```
