### ISSUE TITLE
Last reset missing

### ISSUE THREAD

**Issue by toledobastos** [StephanJoubert/home_assistant_solarman#44]
The sensors are working flawlessly, but the energy panel can’t display them correctly because they don’t seem to reset at midnight. This is the error message I get from the Energy panel:

The following entities have state class 'measurement' but 'last_reset' is missing:
sensor.solis_local_daily_generation

The reported figures are therefore cumulative instead of daily. Am I missing something here? The plots in your example show the Energy tab working correctly.

**Comment by michaljonik** [comment]
I had the same issue. I was getting a negative spike every midnight. 
Also my custom calculations of energy bought and sold were messy - most likely because of very less frequent updates during nights when there was is production.
So I ended up encapsulating _solarman_total_production_ into a utility meter and with this new entity it works perfectly:
```
utility_meter:
  daily_energy_generated:
    source: sensor.solarman_total_production
    name: Daily energy production
    cycle: daily
```
