### ISSUE TITLE
HYD3000 / HYD6000 protocol

### ISSUE THREAD

**Issue by paqp** [StephanJoubert/home_assistant_solarman#45]
Hi! I started from your files to map my HYD6000. 
After weeks of researches I mapped a 77 components of inverter!
My model is branded "ZCS AZZURRO" but I saw that's the same for unbranded ones.
And this is what I got:
![solarman1](https://user-images.githubusercontent.com/73260000/167284295-7df6a444-7cb6-46c7-a431-e5630c77be87.png)
![solarman2](https://user-images.githubusercontent.com/73260000/167284296-79741520-f7d0-443a-a347-f9101c0ca619.png)
![solarman3](https://user-images.githubusercontent.com/73260000/167284297-332ed07d-8b40-4545-aaa3-3ec4e65db7ce.png)

A lot of datas!
This inverter has NO separate entities to show charging/discharging batteries or giving/getting energy from grid, but it has one entity for grid in/out and one for batteries charge/discharge. 
So if, for example, entity  "batteries charge/discharge power" has a positive value, batteries are charging, if it has negative value they are discharging.
So I'm thinking how I could use this to integrate with HA because it requires 2 distinct entities for grid and for batteries.

I hope it will help
[hyd3000-6000.txt](https://github.com/StephanJoubert/home_assistant_solarman/files/8646417/hyd3000-6000.txt)

Cheers!
Paq

**Comment by samdunne** [comment]
Hey Paq. I am using the same inverter and have done more or less the same as what you have above. Have you had problems with massive spikes in your data?

**Comment by paqpal** [comment]
yes, more or less... I'm using filter in HA.
Are you using the "daily" parameters in the Energy configuration for grid and batteries?

**Comment by samdunne** [comment]
I am. Would you be able to share your filter and config for the energy dashboard?

**Comment by paqp** [comment]
This is my configuration:

```
  - platform: filter
    name: "Pannelli Produzione Istantanea - filtrato"
    entity_id: sensor.solarman_pv_instant_generated_pw
    filters:
      - filter: range
        lower_bound: 0.0
        upper_bound: 10.0

  - platform: filter
    name: "Battery Percentage - filtered"
    entity_id: sensor.solarman_battery_percentage
    filters:
      - filter: range
        lower_bound: 0.0
        upper_bound: 100.0

  - platform: integration
    source: sensor.pannelli_produzione_istantanea_filtrato
    name: energy_spent
    unit_prefix: k
    round: 2
```
I use the last one `- platform: integration` for instant generated power conversion from kW to kWh.
    


![energyconf](https://user-images.githubusercontent.com/73260000/167409706-1b778e4d-2d9a-458e-9ee9-a7e0bcad6992.png)

It's not perfect but it's working. I'm changing something everyday.
This is the last file I made.
[HYD3000-6000 parameters-v2.txt](https://github.com/StephanJoubert/home_assistant_solarman/files/8651774/HYD3000-6000.parameters-v2.txt)
