### ISSUE TITLE
Way to control Deye Inverter

### ISSUE THREAD

**Issue by Ramaddan** [StephanJoubert/home_assistant_solarman#504]
Hi,

First, one of the best Home Assistant addons out there for me.

I am using a Deye inverter SUN-8K-SG01LP1

I was wondering if there is a way to control anything on the inverter, as in change any setting from Home Assistant.

If there is, then a person can do many interesting things though Home Assistant.

Thanks

**Comment by ChrisBGL** [comment]
Yes, please integrate control. F.e. (de)active time of use in inverter config.

**Comment by Ramaddan** [comment]
Yes, one idea in mind is to be able to turn ON and OFF the gen force, remotely

Currently, have to go down and up a building in case I need to force turn ON the generator

**Comment by krasnoukhov** [comment]
I came up with a config to turn gen on/off for the deye invertor. I chose `custom_parameters.yaml` for the configuration, and changed the file slightly to this:

```yaml
requests:
  - start: 0x0003
    end: 0x0070
    mb_functioncode: 0x03
  - start: 0x0096
    end: 0x00f9
    mb_functioncode: 0x03
  - start: 0x00FA
    end: 0x0146
    # end: 0x0117
    mb_functioncode: 0x03

parameters:
 # ... all the parameters from deye_hybrid ...
 - group: Settings
   items:
    - name: "Grid Charge Ampere"
      class: "current"
      uom: "A"
      scale: 1
      rule: 1
      registers: [0x00E6]
      icon: 'mdi:current-dc'
    - name: "Gen Force"
      class: ""
      uom: ""
      state_class: ""
      scale: 1
      rule: 1
      registers: [0x0146]
      icon: 'mdi:generator-stationary'
      lookup:
        - key: 0
          value: "Off"
        - key: 8192
          value: "On"
```

`requests` needs a change to be able to query 0x0146 which is "gen force" option. And then I have template switch that uses the service to turn on/off:

```yaml
switch:
  - platform: template
    switches:
      gen_force:
        friendly_name: "Deye Gen Force"
        value_template: |
          {{ is_state("sensor.deye_gen_force", "On") }}
        turn_on:
          service: solarman.write_multiple_holding_registers
          data:
            register: 326
            values: "{{ [8192] }}"
        turn_off:
          service: solarman.write_multiple_holding_registers
          data:
            register: 326
            values: "{{ [0] }}"
        icon_template: >-
          {% if is_state("sensor.deye_gen_force", "On") %}
            mdi:engine
          {% else %}
            mdi:engine-off
          {% endif %}
```
