### ISSUE TITLE
Afore Inverter

### ISSUE THREAD

**Issue by olovfr** [StephanJoubert/home_assistant_solarman#545]
My Serial number starts with 27. I manage to connect to my Afore Inverter using the definition for Afore inverters. But there is no menu item on the inverter to change to modbus like it suggests in the definition. All values are wrong that I receive.
Is there anything I can do to make the connection working.

**Comment by ketoha** [comment]
What afore inverter do you have? And what version of solarman are you using?

**Comment by olovfr** [comment]
My inverter is bnt005ktl and solarman version is 1.4.3
I have been able to connect directly by modbus rtu also but i recieve the same wrong values. I found in the inverter to set communication port 2 to modbus but that didnt help. What menu changes rs485 to modbus?

**Comment by Bielik1984** [comment]
Today I finally managed to connect my AFORE BNT005KTL to Home Assistant locally using an LSW3 logger and the StephanJoubert Solarman integration, after struggling with this for four years!

My inverter has no menu option to switch from RS485 to Modbus, but local communication works without changing that setting.

Save the configuration below as `custom_parameters.yaml` in:

`/config/custom_components/solarman/inverter_definitions/`

Then select `custom_parameters.yaml` in the Solarman integration settings and restart Home Assistant.

This profile uses the AFORE T6 register map. Phase voltages and grid frequency have been confirmed against live readings. Further validation is still in progress, especially for the energy counters, so please compare those with your inverter readings before using them in the Energy dashboard.

```yaml
# AFORE BNT005KTL T6 — read-only. Numeric sensors require class and uom, even when null.
# Verified live: 507-509, 513. Other ranges require validation.
# 32-bit lists: low word first. Upstream rule 2 has a one-unit negative decoding error.
# Energy: verify 0.1 kWh scaling against inverter before using statistics.
requests:
  - start: 0
    end: 53
    mb_functioncode: 4
  - start: 500
    end: 528
    mb_functioncode: 4
  - start: 553
    end: 560
    mb_functioncode: 4
  - start: 1000
    end: 1015
    mb_functioncode: 4
  - start: 2500
    end: 2500
    mb_functioncode: 4
  - start: 2514
    end: 2515
    mb_functioncode: 4
  - start: 3000
    end: 3027
    mb_functioncode: 4
parameters:
  - group: solar
    items:
      - name: Afore Model
        rule: 5
        registers:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
        isstr: true
      - name: Afore Serial number
        rule: 5
        registers:
          - 41
          - 42
          - 43
          - 44
          - 45
          - 46
          - 47
          - 48
        isstr: true
      - name: Afore Rated power
        rule: 1
        registers:
          - 8
          - 7
        uom: W
        class: power
        state_class: measurement
        scale: 1
      - name: Afore Hardware version raw
        rule: 1
        registers:
          - 15
        scale: 1
        class: null
        uom: null
      - name: Afore Protocol version raw
        rule: 1
        registers:
          - 20
        scale: 1
        class: null
        uom: null
      - name: Afore Master firmware raw
        rule: 1
        registers:
          - 25
        scale: 1
        class: null
        uom: null
      - name: Afore Slave firmware raw
        rule: 1
        registers:
          - 30
        scale: 1
        class: null
        uom: null
      - name: Afore HMI firmware raw
        rule: 1
        registers:
          - 35
        scale: 1
        class: null
        uom: null
      - name: Afore CPLD firmware raw
        rule: 1
        registers:
          - 40
        scale: 1
        class: null
        uom: null
      - name: Afore Country code
        rule: 1
        registers:
          - 49
        scale: 1
        class: null
        uom: null
      - name: Afore Maximum AC current
        rule: 1
        registers:
          - 51
          - 50
        uom: A
        class: current
        state_class: measurement
        scale: 0.01
      - name: Afore DC bus voltage
        rule: 1
        registers:
          - 500
        uom: V
        class: voltage
        state_class: measurement
        scale: 0.1
      - name: Afore Negative DC bus voltage
        rule: 1
        registers:
          - 501
        uom: V
        class: voltage
        state_class: measurement
        scale: 0.1
      - name: Afore Insulation resistance
        rule: 1
        registers:
          - 502
        uom: kΩ
        state_class: measurement
        scale: 1
        class: null
      - name: Afore Leakage current
        rule: 1
        registers:
          - 503
        uom: mA
        class: current
        state_class: measurement
        scale: 1
      - name: Afore L1 DC injection
        rule: 2
        registers:
          - 504
        uom: mA
        class: current
        state_class: measurement
        scale: 1
      - name: Afore L1 Voltage
        rule: 1
        registers:
          - 507
        uom: V
        class: voltage
        state_class: measurement
        scale: 0.1
      - name: Afore L1 Current
        rule: 2
        registers:
          - 510
        uom: A
        class: current
        state_class: measurement
        scale: 0.01
      - name: Afore L1 Frequency
        rule: 1
        registers:
          - 513
        uom: Hz
        class: frequency
        state_class: measurement
        scale: 0.01
      - name: Afore L1 Active power
        rule: 2
        registers:
          - 517
          - 516
        uom: W
        class: power
        state_class: measurement
        scale: 1
      - name: Afore L2 DC injection
        rule: 2
        registers:
          - 505
        uom: mA
        class: current
        state_class: measurement
        scale: 1
      - name: Afore L2 Voltage
        rule: 1
        registers:
          - 508
        uom: V
        class: voltage
        state_class: measurement
        scale: 0.1
      - name: Afore L2 Current
        rule: 2
        registers:
          - 511
        uom: A
        class: current
        state_class: measurement
        scale: 0.01
      - name: Afore L2 Frequency
        rule: 1
        registers:
          - 514
        uom: Hz
        class: frequency
        state_class: measurement
        scale: 0.01
      - name: Afore L2 Active power
        rule: 2
        registers:
          - 519
          - 518
        uom: W
        class: power
        state_class: measurement
        scale: 1
      - name: Afore L3 DC injection
        rule: 2
        registers:
          - 506
        uom: mA
        class: current
        state_class: measurement
        scale: 1
      - name: Afore L3 Voltage
        rule: 1
        registers:
          - 509
        uom: V
        class: voltage
        state_class: measurement
        scale: 0.1
      - name: Afore L3 Current
        rule: 2
        registers:
          - 512
        uom: A
        class: current
        state_class: measurement
        scale: 0.01
      - name: Afore L3 Frequency
        rule: 1
        registers:
          - 515
        uom: Hz
        class: frequency
        state_class: measurement
        scale: 0.01
      - name: Afore L3 Active power
        rule: 2
        registers:
          - 521
          - 520
        uom: W
        class: power
        state_class: measurement
        scale: 1
      - name: Afore AC active power
        rule: 2
        registers:
          - 523
          - 522
        uom: W
        class: power
        state_class: measurement
        scale: 1
      - name: Afore AC reactive power
        rule: 2
        registers:
          - 525
          - 524
        uom: var
        class: reactive_power
        state_class: measurement
        scale: 1
      - name: Afore Power factor
        rule: 2
        registers:
          - 526
        scale: 0.001
        class: null
        uom: null
      - name: Afore AC apparent power
        rule: 1
        registers:
          - 528
          - 527
        uom: VA
        class: apparent_power
        state_class: measurement
        scale: 1
      - name: Afore PV total power
        rule: 1
        registers:
          - 554
          - 553
        uom: W
        class: power
        state_class: measurement
        scale: 1
      - name: Afore PV1 Voltage
        rule: 1
        registers:
          - 555
        uom: V
        class: voltage
        state_class: measurement
        scale: 0.1
      - name: Afore PV1 Current
        rule: 1
        registers:
          - 556
        uom: A
        class: current
        state_class: measurement
        scale: 0.01
      - name: Afore PV1 Power
        rule: 1
        registers:
          - 557
        uom: W
        class: power
        state_class: measurement
        scale: 1
      - name: Afore PV2 Voltage
        rule: 1
        registers:
          - 558
        uom: V
        class: voltage
        state_class: measurement
        scale: 0.1
      - name: Afore PV2 Current
        rule: 1
        registers:
          - 559
        uom: A
        class: current
        state_class: measurement
        scale: 0.01
      - name: Afore PV2 Power
        rule: 1
        registers:
          - 560
        uom: W
        class: power
        state_class: measurement
        scale: 1
      - name: Afore Daily AC energy
        rule: 1
        registers:
          - 1000
        uom: kWh
        class: energy
        state_class: total_increasing
        scale: 0.1
      - name: Afore Daily PV energy
        rule: 1
        registers:
          - 1007
          - 1006
        uom: kWh
        class: energy
        state_class: total_increasing
        scale: 0.1
      - name: Afore Daily PV1 energy
        rule: 1
        registers:
          - 1008
        uom: kWh
        class: energy
        state_class: total_increasing
        scale: 0.1
      - name: Afore Daily PV2 energy
        rule: 1
        registers:
          - 1009
        uom: kWh
        class: energy
        state_class: total_increasing
        scale: 0.1
      - name: Afore Total AC energy
        rule: 1
        registers:
          - 1015
          - 1014
        uom: kWh
        class: energy
        state_class: total_increasing
        scale: 0.1
      - name: Afore Run state code
        rule: 1
        registers:
          - 2500
        scale: 1
        class: null
        uom: null
      - name: Afore Inner temperature
        rule: 2
        registers:
          - 2514
        uom: °C
        class: temperature
        state_class: measurement
        scale: 0.1
      - name: Afore Transformer temperature
        rule: 2
        registers:
          - 2515
        uom: °C
        class: temperature
        state_class: measurement
        scale: 0.1
      - name: Afore PV error 1 mask
        rule: 1
        registers:
          - 3001
          - 3000
        scale: 1
        class: null
        uom: null
      - name: Afore PV error 2 mask
        rule: 1
        registers:
          - 3003
          - 3002
        scale: 1
        class: null
        uom: null
      - name: Afore Grid error mask
        rule: 1
        registers:
          - 3009
          - 3008
        scale: 1
        class: null
        uom: null
      - name: Afore DC error 1 mask
        rule: 1
        registers:
          - 3013
          - 3012
        scale: 1
        class: null
        uom: null
      - name: Afore DC error 2 mask
        rule: 1
        registers:
          - 3015
          - 3014
        scale: 1
        class: null
        uom: null
      - name: Afore AC error mask
        rule: 1
        registers:
          - 3017
          - 3016
        scale: 1
        class: null
        uom: null
      - name: Afore System error 1 mask
        rule: 1
        registers:
          - 3019
          - 3018
        scale: 1
        class: null
        uom: null
      - name: Afore System error 2 mask
        rule: 1
        registers:
          - 3021
          - 3020
        scale: 1
        class: null
        uom: null
      - name: Afore Permanent error mask
        rule: 1
        registers:
          - 3023
          - 3022
        scale: 1
        class: null
        uom: null
      - name: Afore Internal warning mask
        rule: 1
        registers:
          - 3025
          - 3024
        scale: 1
        class: null
        uom: null
      - name: Afore External warning mask
        rule: 1
        registers:
          - 3027
          - 3026
        scale: 1
        class: null
        uom: null
```
