### ISSUE TITLE
Failing to retrieve any data from deye_sg04lp3 when batterie reports temperature -100*C

### ISSUE THREAD

**Issue by suplstfdo** [StephanJoubert/home_assistant_solarman#632]
I used the integration with my deye_sg04lp3 12K with solar pannels only and everything worked flawless. After a while i extended the installation by a felicity battery storage, to store energy for the nights. After installing the battery the integration broke and did not deliver any data.

I noticed that the inverter does report a battery temperature of -100°C on the local UI. I assumed this is the case, either because I did not install the external temperature sensor, or because the battery does not report its temperature correctly via CAN bus to the inverter. In the homeassistant logs I found a log entry, stating that the parsing of the data failed because battery temperature measurement was invalid. This makes sense, because the validation range in the config is 1-99°C

```
      - name: "Battery Temperature"
        class: "temperature"
        state_class: "measurement"
        uom: "°C"
        scale: 0.1
        rule: 1
        offset: 1000
        registers: [0x024A]
        icon: "mdi:battery"
        validation:
          min: 1
          max: 99
```

What puzzles me is, that even though the inverter definition file does not state the "invalidate_all" tag for the battery temperature option, this seemed to invalidate the whole dataset for me. At least all entities where "Not available". I fixed the problem on my installation by changing the "Battery Temperature" -> "validation" -> "min" value to -101.
