### ISSUE TITLE
Querying [xxxx - yyyy] failed with exception [error: 'I' format requires 0 <= number <= 4294967295]'

### ISSUE THREAD

**Issue by gardiol** [StephanJoubert/home_assistant_solarman#668]
I am trying to read at least one data from my Chint inverter connected with Solarman:

This is my custom yaml:
```
requests:
  - start: 0x1010
    end:  0x1020
    mb_functioncode: 0x03

parameters:
 - group: solar
   items:
    - name: "PV1 Voltage"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 1
      rule: 1
      registers: [0x1010]
      icon: 'mdi:solar-power'
```

The Modbus data i got from the PDF Chint sent me.

The error i get in the logs is:
```
Logger: custom_components.solarman.solarman
Source: custom_components/solarman/solarman.py:88
'Querying [4112 - 4128] failed with exception [error: 'I' format requires 0 <= number <= 4294967295]'
```

Then of course, i get the failed read attempts.

Is it some error from my side?
