### ISSUE TITLE
Data Connection Fails for Sofar HYD 6000-ES

### ISSUE THREAD

**Issue by changeableface** [StephanJoubert/home_assistant_solarman#80]
I have installed and followed instructions, but unfortunately, upon choosing Sofar configuration data connection fails. I have poked around a bit and failed to make much headway. 

Some information to help debug; 
- Inverter Sofar HYD 6000-ES, firmware G330
- Wifi Stick Logger, firmware LSW3_15_FFFF_1.0.65
- Using the latest Home Assistant running via docker-compose, 
- Confirmed the container can ping the logger

Appreciate this might not be an issue you're motivated to fix, but I would obviously be super keen to see this working and happy to work with you on a solution. 

Please let me know If any further information would help diagnose this issue.

**Comment by igieon** [comment]
Can you try as cusotm config file which i provide in pull request https://github.com/StephanJoubert/home_assistant_solarman/pull/82

**Comment by changeableface** [comment]
Hi! 

Thanks for the pull request, unfortunately, it doesn't appear to work. 

<img width="458" alt="Screenshot 2022-08-08 at 14 54 07" src="https://user-images.githubusercontent.com/840144/183435659-1ff554cd-3a1d-40ae-bc7b-8f672b7c6a20.png">

Are there any log files I can provide to give better feedback?

Thanks again, 
- Matt

**Comment by igieon** [comment]
I just look into this project https://github.com/AndyWhittaker/HYD6000/blob/master/sofar.py.

ANd based on this can you test in custom config:
```
requests:
  - start: 0x0210
    end: 0x0215
    mb_functioncode: 0x03
parameters:
  - group: Battery
      items:
        - name: "Battery Temperature"
          class: "temperature"
          state_class: "measurement"
          uom: "°C"
          scale: 1
          rule: 2
          registers: [ 0x0211 ]
          icon: 'mdi:battery'
        - name: "Grid_IO_Pwr"
          class: "power"
          state_class: "measurement"
          uom: "W"
          scale: 10
          rule: 1
          registers: [ 0x0212 ]
          icon: 'mdi:solar-power'
        - name: "House_Consumption_Pwr"
          class: "power"
          state_class: "measurement"
          uom: "W"
          scale: 10
          rule: 1
          registers: [ 0x0213 ]
          icon: 'mdi:solar-power'  
        - name: "Internal_IO_Pwr"
          class: "power"
          state_class: "measurement"
          uom: "W"
          scale: 10
          rule: 1
          registers: [ 0x0214 ]
          icon: 'mdi:solar-power'
        - name: "PV_Generation_Pwr"
          class: "power"
          state_class: "measurement"
          uom: "W"
          scale: 10
          rule: 1
          registers: [ 0x0215 ]
          icon: 'mdi:solar-power'                
```
If this works you can based on that python file add aditional info
