### ISSUE TITLE
Deye Micro Inverter SUN2000G3

### ISSUE THREAD

**Issue by alessandroo23** [StephanJoubert/home_assistant_solarman#86]
Has anyone managed to integrate Deye SUN2000G3 microinverters?

**Comment by leonardolisboa** [comment]
Here https://github.com/StephanJoubert/home_assistant_solarman/issues/46

**Comment by kababoom** [comment]
I have the 1600 version and it's working fine with below config, of course you need to add the deye_4mppt.yaml to the inverters definitions..

There's just one thing that I cannot change and that's the interval, it stays on every 5 minutes whatever setting I change...
```
  - platform: solarman
    name: DEYE
    inverter_host: 192.168.10.90
    inverter_port: 8899
    inverter_serial: 4130xxxxxx
    inverter_mb_slaveid: 1
    scan_interval: 30
    lookup_file: deye_4mppt.yaml

  - platform: template
    sensors:
      deye_pv1_power:
        unit_of_measurement: W
        device_class: power
        value_template: "{{ states('sensor.deye_pv1_voltage') | float * states('sensor.deye_pv1_current') | float }}"

      deye_pv2_power:
        unit_of_measurement: W
        device_class: power
        value_template: "{{ states('sensor.deye_pv2_voltage') | float * states('sensor.deye_pv2_current') | float }}"

      deye_pv3_power:
        unit_of_measurement: W
        device_class: power
        value_template: "{{ states('sensor.deye_pv3_voltage') | float * states('sensor.deye_pv3_current') | float }}"

      deye_pv4_power:
        unit_of_measurement: W
        device_class: power
        value_template: "{{ states('sensor.deye_pv4_voltage') | float * states('sensor.deye_pv4_current') | float }}"

```
